-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Tempo de geração: 22/05/2025 às 02:33
-- Versão do servidor: 9.1.0
-- Versão do PHP: 8.3.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `royalmotorsdb`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `adm`
--

DROP TABLE IF EXISTS `adm`;
CREATE TABLE IF NOT EXISTS `adm` (
  `idAdm` int NOT NULL AUTO_INCREMENT,
  `nomeAdm` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `cpfAdm` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `senhaAdm` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  PRIMARY KEY (`idAdm`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Despejando dados para a tabela `adm`
--

INSERT INTO `adm` (`idAdm`, `nomeAdm`, `cpfAdm`, `senhaAdm`) VALUES
(1, 'Kayky Bezerra', '47859738899', '202cb962ac59075b964b07152d234b70');

-- --------------------------------------------------------

--
-- Estrutura para tabela `carros`
--

DROP TABLE IF EXISTS `carros`;
CREATE TABLE IF NOT EXISTS `carros` (
  `idCarro` int NOT NULL AUTO_INCREMENT,
  `modeloCarro` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `marcaCarro` varchar(20) COLLATE utf8mb3_unicode_ci NOT NULL,
  `anoCarro` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `motorCarro` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `kmCarro` int NOT NULL,
  `valorCustoCarro` varchar(20) COLLATE utf8mb3_unicode_ci NOT NULL,
  `valorVendaCarro` varchar(20) COLLATE utf8mb3_unicode_ci NOT NULL,
  `corCarro` varchar(20) COLLATE utf8mb3_unicode_ci NOT NULL,
  `categoriaCarro` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `descCarro` mediumtext COLLATE utf8mb3_unicode_ci NOT NULL,
  `dtaCadastroCarro` date NOT NULL,
  `statusCarro` varchar(20) COLLATE utf8mb3_unicode_ci NOT NULL,
  `imgPrincipalCarro` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `imgCarro2` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `imgCarro3` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `imgCarro4` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  PRIMARY KEY (`idCarro`)
) ENGINE=MyISAM AUTO_INCREMENT=125 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Despejando dados para a tabela `carros`
--

INSERT INTO `carros` (`idCarro`, `modeloCarro`, `marcaCarro`, `anoCarro`, `motorCarro`, `kmCarro`, `valorCustoCarro`, `valorVendaCarro`, `corCarro`, `categoriaCarro`, `descCarro`, `dtaCadastroCarro`, `statusCarro`, `imgPrincipalCarro`, `imgCarro2`, `imgCarro3`, `imgCarro4`) VALUES
(120, 'X3', 'BMW', '2021', '2.0 16V HÍBRIDO XDRIVE30E STEPTRONIC', 20000, '78000', '624936', 'roxo', 'SUVS', 'BMW X3 xDRIVE30e 2.0 HÍBRIDO – SOFISTICAÇÃO, EFICIÊNCIA E TRAÇÃO INTELIGENTE EM UM SÓ SUV\r\nO equilíbrio perfeito entre potência, tecnologia e consciência ambiental. Um SUV premium com desempenho esportivo e eficiência híbrida. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nMotorização: 2.0 TwinPower Turbo + motor elétrico (híbrido plug-in) – 292 cv combinados\r\nTorque: 42,8 kgfm\r\nCâmbio automático Steptronic de 8 marchas com paddle shifts\r\nTração integral xDrive inteligente\r\nAutonomia elétrica de até 50 km (modo EV)\r\nAceleração de 0 a 100 km/h em 6,1 segundos\r\nSuspensão com acerto esportivo e conforto premium\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia iDrive com tela sensível ao toque e conectividade sem fio\r\nPainel digital BMW Live Cockpit Professional\r\nAr-condicionado digital com controle de 3 zonas\r\nAssistentes de condução (controle de cruzeiro adaptativo, assistente de faixa, frenagem de emergência)\r\nChave presencial com partida por botão\r\nFaróis Full LED com acendimento automático\r\nBancos em couro com ajustes elétricos e memória\r\nPorta-malas com abertura elétrica e função mãos-livres\r\nRodas de liga leve BMW aro 19\"\r\n\r\nVeículo híbrido com excelente desempenho e baixo consumo\r\nRevisado, com documentação em dia e procedência garantida\r\nDisponível na Apolo Veículos – entre em contato e agende seu test drive', '2025-05-22', 'disponivel', '8e9e785c568249483edcd5d11c5b4b5f.jpg', '6e815f03960d1bfbc542701799ca3c54.jpg', '07db32499d746d4fc3c3baea99e4945d.jpg', 'ff36886a32f0fafc49686fb604c16a69.jpg'),
(117, 'M3', 'BMW', '2023', '3.0 I6 TWINTURBO GASOLINA COMPETITION M STEPTRONIC', 4300, '649000', '749000', 'verde', 'SEDANS', 'BMW M3 COMPETITION 3.0 TWINTURBO – PURA ADRENALINA COM TECNOLOGIA ALEMÃ DE PONTA\nO ícone da divisão ///M da BMW, feito para quem exige o máximo em desempenho, precisão e esportividade. Um verdadeiro esportivo para as ruas. Disponível na Apolo Veículos.\n\nDestaques do veículo:\nAno/Modelo: 2022 \nMotorização: 3.0 I6 TwinPower Turbo a gasolina – 510 cv\nTorque: 66,3 kgfm\nCâmbio automático M Steptronic de 8 marchas com paddle shifts\nAceleração de 0 a 100 km/h em apenas 3,9 segundos\nTração traseira (RWD) com diferencial ativo M\nFreios M de alta performance e suspensão adaptativa M\nPacote Competition: visual exclusivo, maior potência e acerto esportivo refinado\n\nTecnologia e Conforto:\nPainel 100% digital com layout M\nCentral multimídia BMW Live Cockpit com tela de 12,3\"\nHead-Up Display com informações de condução\nBancos esportivos M com ajustes elétricos e memória\nVolante M multifuncional com acabamento em couro\nAr-condicionado digital com controle de 3 zonas\nSistema de som Harman Kardon premium\nAssistentes de condução (alerta de colisão, saída de faixa, frenagem autônoma, entre outros)\nRodas M de liga leve aro 19” (dianteiras) e 20” (traseiras)\n\nVeículo esportivo de alto padrão, com histórico aprovado e revisado\nDocumentação em dia\nDisponível na Apolo Veículos\nEntre em contato e agende uma visita – atendimento rápido e especializado', '2025-05-22', 'disponivel', '8cf93bee7f02d44019cb728358ba42e4.jpg', 'a65a9bfb741725f574f833f14d9aa73d.jpg', 'e4d8b5e80eb208181992ce3f680ac041.jpg', '6dec5d7633bbcc80a9a041d35aad5edc.jpg'),
(111, 'CIVIC', 'Honda', '2024', '2.0 DI VTEC TURBO GASOLINA TYPE R MANUAL', 2310, '200000', '292000', 'Branco', 'SEDANS', 'HONDA CIVIC TYPE R 2.0 VTEC TURBO – PERFORMANCE PURA COM DNA DE PISTA\r\nO esportivo lendário da Honda em sua versão mais potente e refinada. Combinação perfeita entre tecnologia, engenharia japonesa e emoção ao volante. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2024\r\nMotor: 2.0 VTEC Turbo a gasolina – 297 cv\r\nTorque: 42,8 kgfm\r\nCâmbio manual de 6 marchas com rev-match (igualador de rotações)\r\nTração dianteira com diferencial de deslizamento limitado (LSD)\r\nSuspensão adaptativa com acerto esportivo\r\nAceleração de 0 a 100 km/h em aproximadamente 5,4 segundos\r\nVelocidade máxima superior a 270 km/h\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia com tela de 9\" e conectividade sem fio (Android Auto e Apple CarPlay)\r\nPainel digital com modo de exibição exclusivo Type R\r\nAr-condicionado digital Dual Zone\r\nBancos esportivos tipo concha com acabamento em camurça vermelha\r\nVolante esportivo com costura vermelha e acabamento premium\r\nControles de estabilidade (VSA) e tração (TCS) com modo de condução ajustável (Comfort, Sport e +R)\r\nSistema de som premium Bose com 12 alto-falantes\r\nPacote completo de segurança Honda Sensing\r\n\r\nVeículo zero km, com garantia de fábrica\r\nUnidade exclusiva na Apolo Veículos\r\nEntre em contato e garanta já esse ícone da performance japonesa\r\nAgende uma visita e sinta a emoção de dirigir um verdadeiro Type R\r\n\r\n', '2025-05-22', 'disponivel', '45136655f38c2e2fb1ef6633b7305102.jpg', '25d2417626313fb3b9cb89e5031c92a6.jpg', '4126a67164c9152821be430c25c556e6.jpg', '464d8a86e17daf8dbf78d68a56416e72.jpg'),
(105, 'Nivus', 'Volkswagen', '2024', '1.0 200 TSI TOTAL FLEX HIGHLINE AUTOMÁTICO', 3000, '120000', '170000', 'Vermelho', 'SUVS', 'VOLKSWAGEN NIVUS 1.0 200 TSI HIGHLINE AUTOMÁTICO – DESIGN MODERNO, TECNOLOGIA E PERFORMANCE TURBO\r\nO SUV cupê da Volkswagen que se destaca pelo visual esportivo, excelente desempenho e alta conectividade. Versão topo de linha disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2021 (ou atualize conforme o modelo)\r\nMotor: 1.0 TSI Flex – 128 cv (etanol) / 116 cv (gasolina)\r\nTorque: 20,4 kgfm com injeção direta\r\nCâmbio automático de 6 marchas\r\nAceleração de 0 a 100 km/h em 10 segundos\r\nConsumo médio: até 14 km/l na estrada (gasolina)\r\nPorta-malas com 415 litros\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia VW Play com tela de 10,1\" sensível ao toque\r\nPainel digital (Active Info Display)\r\nChave presencial com partida por botão (Keyless Entry & Go)\r\nAr-condicionado digital\r\nControle de estabilidade (ESC) e tração (ASR)\r\nAssistente de partida em rampa (HSA)\r\nSensor de chuva e crepuscular\r\nBancos em couro, volante multifuncional e acabamento premium\r\nSistema de frenagem automática pós-colisão\r\n\r\nVeículo periciado e com garantia\r\nDocumentação em dia\r\nNa Apolo Veículos, você encontra qualidade, procedência e as melhores condições\r\nEntre em contato com nossa equipe e agende seu test drive', '2025-05-20', 'disponivel', '80df0b47adfd89f1048f7d5f98e30be0.jpg', '3ef3c2861e6f68fdaaf1eb0ca7296c74.jpg', '167d2da558702c4b58018932b9a66c31.jpg', '41f5b9aacc7253d9da4cec57c9bc531f.jpg'),
(108, 'CIVIC', 'Honda', '2024', '2.0 DI VTEC TURBO GASOLINA TYPE R MANUAL', 2310, '200000', '314000', 'Branco', 'SEDANS', 'HONDA CIVIC TYPE R 2.0 VTEC TURBO – PERFORMANCE PURA COM DNA DE PISTA\r\nO esportivo lendário da Honda em sua versão mais potente e refinada. Combinação perfeita entre tecnologia, engenharia japonesa e emoção ao volante. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2024\r\nMotor: 2.0 VTEC Turbo a gasolina – 297 cv\r\nTorque: 42,8 kgfm\r\nCâmbio manual de 6 marchas com rev-match (igualador de rotações)\r\nTração dianteira com diferencial de deslizamento limitado (LSD)\r\nSuspensão adaptativa com acerto esportivo\r\nAceleração de 0 a 100 km/h em aproximadamente 5,4 segundos\r\nVelocidade máxima superior a 270 km/h\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia com tela de 9\" e conectividade sem fio (Android Auto e Apple CarPlay)\r\nPainel digital com modo de exibição exclusivo Type R\r\nAr-condicionado digital Dual Zone\r\nBancos esportivos tipo concha com acabamento em camurça vermelha\r\nVolante esportivo com costura vermelha e acabamento premium\r\nControles de estabilidade (VSA) e tração (TCS) com modo de condução ajustável (Comfort, Sport e +R)\r\nSistema de som premium Bose com 12 alto-falantes\r\nPacote completo de segurança Honda Sensing\r\n\r\nVeículo zero km, com garantia de fábrica\r\nUnidade exclusiva na Apolo Veículos\r\nEntre em contato e garanta já esse ícone da performance japonesa\r\nAgende uma visita e sinta a emoção de dirigir um verdadeiro Type R\r\n\r\n', '2025-05-22', 'disponivel', 'f640da49ff013a385e49aa242e5640ad.jpg', '11c9f65316e5813f6dd96a5628008a8f.jpg', '4b0c312722b7ae5db68563b8aae4fe85.jpg', '132d25cc9db5e36cb43c551022666126.jpg'),
(83, 'Lancer Evolution', 'Mitsubishi', '2013', '2.0 EVOLUTION X 4X4 16V TURBO INTERCOOLER GASOLINA', 12000, '23000', '80000', 'branco', 'SEDANS', 'Mitsubishi Lancer Evolution X 2013/2014\r\n\r\n\r\nDestaques do veículo:\r\n Ano/Modelo: 2013/2014\r\nMotor: 2.0 Turbo Intercooler – 295 cv \r\nTorque: 37,3 kgfm p Tração integral 4x4 (AWD)\r\nCâmbio automático de dupla embreagem (SST) de 6 marchas\r\nSuspensão esportiva \r\nAceleração de 0 a 100 km/h: 5,4 segundos!\r\n\r\n\r\nTecnologia:\r\n\r\nPaddle Shifters no volante para uma condução mais esportiva\r\nBancos esportivos\r\nRecaro para máximo suporte e estilo\r\nCentral multimídia com Bluetooth e sistema de som premium Ar-condicionado digital Dual Zone', '2025-05-10', 'disponivel', 'dd8e1663c919478dbb74ab3aa2fdaeda.jpg', '8b1690acc2cace882da928eed53fafe0.jpg', '2a8b4bf0c85e8f6c13864b43043feffc.jpg', 'a0df1d0649d05ec0c2a48e6279644cba.jpg'),
(107, 'Compass', 'Jeep', '2022', '1.3 T270 TURBO FLEX LONGITUDE AT6', 0, '130000', '170000', 'Branco', 'SUVS', 'JEEP COMPASS 1.3 T270 TURBO FLEX LONGITUDE AT6 – PERFORMANCE, TECNOLOGIA E SOFISTICAÇÃO EM UM ÚNICO SUV\r\nUm dos SUVs mais completos da categoria, com motor turbo moderno, excelente acabamento e tecnologia embarcada. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2022 (ou atualize conforme o modelo)\r\nMotor: 1.3 T270 Turbo Flex – 185 cv (etanol) / 180 cv (gasolina)\r\nTorque: 27,5 kgfm\r\nCâmbio automático de 6 marchas (AT6)\r\nConsumo médio: até 11,8 km/l na estrada (gasolina)\r\nPorta-malas com 410 litros\r\nDesign robusto com linhas sofisticadas\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia com tela flutuante de 10,1\" com Android Auto e Apple CarPlay sem fio\r\nPainel digital configurável de 10,25\"\r\nChave presencial com partida por botão (Keyless Enter \'n Go)\r\nAr-condicionado digital Dual Zone\r\nControle de estabilidade (ESC), tração (TCS) e assistente de partida em rampa (HSA)\r\nCâmera de ré, sensores de estacionamento e retrovisores elétricos\r\nBancos em couro, volante multifuncional e acabamento refinado\r\n6 airbags e freios ABS com EBD\r\n\r\nVeículo com histórico aprovado, garantia e procedência\r\nDocumentação em dia\r\nVenha conhecer de perto o Jeep Compass na Apolo Veículos\r\nEntre em contato e agende um test drive com um de nossos consultores\r\n\r\n', '2025-05-20', 'vendido', '2b50cc79f791f7a874fabb5b4a4c398f.jpg', '90949fb34ac77bcd18464295881aba61.jpg', '714d72393de1fda2fff26a0070c6473d.jpg', '0966c884baba5544d4a641a2c029deef.jpg'),
(85, 'X6', 'BMW', '2023', '3.0 TWINPOWER GASOLINA XDRIVE40I M SPORT AUTOMÁTIC', 4000, '100000', '150000', 'Preto', 'SUVS', 'BMW X5 xDrive40i M Sport 3.0 Turbo 2023\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2023\r\nMotor: 3.0 TwinPower Turbo de 6 cilindros em linha – 340 cv\r\nTorque: 45,9 kgfm\r\nTração integral inteligente xDrive\r\nCâmbio automático Steptronic de 8 marchas\r\nSuspensão adaptativa M\r\nAceleração de 0 a 100 km/h: 5,5 segundos\r\n\r\nTecnologia:\r\nSistema multimídia iDrive 7.0 com tela curva de 14,9\"\r\nHead-Up Display projetado no para-brisa\r\nFaróis full LED adaptativos com assistente de farol alto\r\nPiloto automático adaptativo com assistente de faixa\r\nSistema de som surround Harman Kardon\r\nCâmera 360° com assistente de estacionamento\r\nChave digital BMW (via smartphone)\r\n\r\nConforto e Estilo:\r\nPacote M Sport com acabamento exclusivo\r\nAr-condicionado digital de 4 zonas\r\nBancos esportivos elétricos com memória e ventilação\r\nTeto solar panorâmico Sky Lounge\r\nRodas de liga leve aro 21” com design M', '2025-05-10', 'disponivel', 'd985f75b6e6ba26a78d6699e5d3df2cf.jpg', '7c9c551122fea01e78893ed97594f9dd.jpg', '286f6ff135a9cd0ff49201d2288bc031.jpg', '69ac8decbe9963f36dbd04834329e01c.jpg'),
(110, 'CIVIC', 'Honda', '2024', '2.0 DI VTEC TURBO GASOLINA TYPE R MANUAL', 2310, '200000', '292000', 'Vermelho', 'SEDANS', 'HONDA CIVIC TYPE R 2.0 VTEC TURBO – PERFORMANCE PURA COM DNA DE PISTA\r\nO esportivo lendário da Honda em sua versão mais potente e refinada. Combinação perfeita entre tecnologia, engenharia japonesa e emoção ao volante. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2024\r\nMotor: 2.0 VTEC Turbo a gasolina – 297 cv\r\nTorque: 42,8 kgfm\r\nCâmbio manual de 6 marchas com rev-match (igualador de rotações)\r\nTração dianteira com diferencial de deslizamento limitado (LSD)\r\nSuspensão adaptativa com acerto esportivo\r\nAceleração de 0 a 100 km/h em aproximadamente 5,4 segundos\r\nVelocidade máxima superior a 270 km/h\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia com tela de 9\" e conectividade sem fio (Android Auto e Apple CarPlay)\r\nPainel digital com modo de exibição exclusivo Type R\r\nAr-condicionado digital Dual Zone\r\nBancos esportivos tipo concha com acabamento em camurça vermelha\r\nVolante esportivo com costura vermelha e acabamento premium\r\nControles de estabilidade (VSA) e tração (TCS) com modo de condução ajustável (Comfort, Sport e +R)\r\nSistema de som premium Bose com 12 alto-falantes\r\nPacote completo de segurança Honda Sensing\r\n\r\nVeículo zero km, com garantia de fábrica\r\nUnidade exclusiva na Apolo Veículos\r\nEntre em contato e garanta já esse ícone da performance japonesa\r\nAgende uma visita e sinta a emoção de dirigir um verdadeiro Type R\r\n\r\n', '2025-05-22', 'disponivel', 'aeacb1c62eafbf287ea8811a6e2559b6.jpg', 'fb57c7d1bb9fb125d2d1407f38774b99.jpg', '41cce17b10a9a0f5145228a8327ce150.jpg', 'c1ae99062da0f350c1b81a080b594191.jpg'),
(109, 'CIVIC', 'Honda', '2024', '2.0 DI VTEC TURBO GASOLINA TYPE R MANUAL', 2310, '200000', '314000', 'Azul', 'SEDANS', 'HONDA CIVIC TYPE R 2.0 VTEC TURBO – PERFORMANCE PURA COM DNA DE PISTA\r\nO esportivo lendário da Honda em sua versão mais potente e refinada. Combinação perfeita entre tecnologia, engenharia japonesa e emoção ao volante. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2024\r\nMotor: 2.0 VTEC Turbo a gasolina – 297 cv\r\nTorque: 42,8 kgfm\r\nCâmbio manual de 6 marchas com rev-match (igualador de rotações)\r\nTração dianteira com diferencial de deslizamento limitado (LSD)\r\nSuspensão adaptativa com acerto esportivo\r\nAceleração de 0 a 100 km/h em aproximadamente 5,4 segundos\r\nVelocidade máxima superior a 270 km/h\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia com tela de 9\" e conectividade sem fio (Android Auto e Apple CarPlay)\r\nPainel digital com modo de exibição exclusivo Type R\r\nAr-condicionado digital Dual Zone\r\nBancos esportivos tipo concha com acabamento em camurça vermelha\r\nVolante esportivo com costura vermelha e acabamento premium\r\nControles de estabilidade (VSA) e tração (TCS) com modo de condução ajustável (Comfort, Sport e +R)\r\nSistema de som premium Bose com 12 alto-falantes\r\nPacote completo de segurança Honda Sensing\r\n\r\nVeículo zero km, com garantia de fábrica\r\nUnidade exclusiva na Apolo Veículos\r\nEntre em contato e garanta já esse ícone da performance japonesa\r\nAgende uma visita e sinta a emoção de dirigir um verdadeiro Type R\r\n\r\n', '2025-05-22', 'disponivel', '6b2dc58fadb8c7f485281ce231712610.jpg', 'e35a6b8592c43426e38d2fb1ca318f57.jpg', '4082bd5a47d9937152f87142574ea256.jpg', '75d56f67d936b4aadae4267ed3a5de48.jpg'),
(114, '540i', 'BMW', '2018', '3.0 24V TURBO GASOLINA M SPORT AUTOMÁTICO', 75, '500000', '879000', 'preto', 'SEDANS', 'BMW 540i M SPORT 3.0 TURBO AUTOMÁTICO – ELEGÂNCIA, DESEMPENHO E TECNOLOGIA ALEMÃ EM UM SÓ CARRO\r\nUm sedã de luxo com espírito esportivo. Potência, sofisticação e conforto em cada detalhe. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2018\r\nMotor: 3.0 TwinPower Turbo a gasolina – 340 cv\r\nTorque: 45,9 kgfm\r\nCâmbio automático esportivo de 8 marchas com paddle shifts\r\nAceleração de 0 a 100 km/h: 4,8 segundos\r\nTração traseira (RWD)\r\nPacote M Sport com visual exclusivo e acabamento refinado\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia iDrive com tela de 10,25\" e comando por gestos\r\nPainel digital personalizável (BMW Live Cockpit)\r\nSistema de som Hi-Fi de alta fidelidade\r\nAr-condicionado digital com controle de 4 zonas\r\nChave presencial com partida por botão (Comfort Access)\r\nFaróis Full LED adaptativos\r\nBancos esportivos com ajustes elétricos e memória\r\nSuspensão M Sport com acerto dinâmico\r\nAssistentes de condução: alerta de mudança de faixa, piloto automático adaptativo, sensor de ponto cego\r\nRodas de liga leve exclusivas M aro 19\"\r\n\r\nVeículo de alto padrão, revisado e com histórico aprovado\r\nDocumentação em dia\r\nDisponível na Apolo Veículos – agende sua visita e conheça de perto o requinte e a força de um verdadeiro BMW\r\n\r\n', '2025-05-22', 'disponivel', 'f89ceb67f5e7af42b729b66471c4a654.jpg', 'a03bddb57466620dd567627590d2ec07.jpg', '6ce50612e682d6e84b7ae0f0e54983a2.jpg', '09aad4ed9f635c4560e54d270254db40.jpg'),
(115, '540i', 'BMW', '2018', '3.0 24V TURBO GASOLINA M SPORT AUTOMÁTICO', 75, '500000', '879000', 'preto', 'SEDANS', 'BMW 540i M SPORT 3.0 TURBO AUTOMÁTICO – ELEGÂNCIA, DESEMPENHO E TECNOLOGIA ALEMÃ EM UM SÓ CARRO\r\nUm sedã de luxo com espírito esportivo. Potência, sofisticação e conforto em cada detalhe. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2018\r\nMotor: 3.0 TwinPower Turbo a gasolina – 340 cv\r\nTorque: 45,9 kgfm\r\nCâmbio automático esportivo de 8 marchas com paddle shifts\r\nAceleração de 0 a 100 km/h: 4,8 segundos\r\nTração traseira (RWD)\r\nPacote M Sport com visual exclusivo e acabamento refinado\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia iDrive com tela de 10,25\" e comando por gestos\r\nPainel digital personalizável (BMW Live Cockpit)\r\nSistema de som Hi-Fi de alta fidelidade\r\nAr-condicionado digital com controle de 4 zonas\r\nChave presencial com partida por botão (Comfort Access)\r\nFaróis Full LED adaptativos\r\nBancos esportivos com ajustes elétricos e memória\r\nSuspensão M Sport com acerto dinâmico\r\nAssistentes de condução: alerta de mudança de faixa, piloto automático adaptativo, sensor de ponto cego\r\nRodas de liga leve exclusivas M aro 19\"\r\n\r\nVeículo de alto padrão, revisado e com histórico aprovado\r\nDocumentação em dia\r\nDisponível na Apolo Veículos – agende sua visita e conheça de perto o requinte e a força de um verdadeiro BMW\r\n\r\n', '2025-05-22', 'disponivel', '5d4005739e1b885a2c637d4f4c00bf84.jpg', 'b4f290fa587c35a755dd3b16f29fdea2.jpg', '5555ba18954984a0a0d5c5f28dce3a2c.jpg', '45ca9a6b4ea746b12c861cceb6f1b2ea.jpg'),
(116, '420i', 'BMW', '2015', '2.0 SPORT GP CABRIO 16V GASOLINA 2P AUTOMÁTICO', 809, '238200', '378000', 'vermelho', 'SEDANS', 'BMW 420i CABRIO SPORT GP 2.0 TURBO AUTOMÁTICO – ESTILO, PERFORMANCE E LIBERDADE AO VOLANTE\nUma combinação de esportividade, sofisticação e prazer em dirigir com o charme de um conversível premium. Viva a experiência de dirigir a céu aberto. Disponível na Apolo Veículos.\n\nDestaques do veículo:\nAno/Modelo: 2015\nMotor: 2.0 TwinPower Turbo a gasolina – 184 cv\nTorque: 27,5 kgfm\nCâmbio automático de 8 marchas com paddle shifts\nAceleração de 0 a 100 km/h em 8,2 segundos\nTração traseira (RWD)\nCapota rígida retrátil totalmente automática\nDesign esportivo com pacote Sport GP exclusivo\n\nTecnologia e Conforto:\nCentral multimídia iDrive com tela de 8,8\" e sistema de navegação\nAr-condicionado digital Dual Zone\nSistema de som Hi-Fi\nBancos em couro com ajustes elétricos e memória\nSensor de estacionamento dianteiro e traseiro com câmera de ré\nFaróis Bi-LED com acendimento automático\nControle de estabilidade (DSC) e tração (DTC)\nModo de condução com ajuste dinâmico (ECO PRO, Comfort e Sport)\nVolante multifuncional esportivo com acabamento em couro\n\nVeículo de alto padrão, revisado e com procedência garantida\nDocumentação em dia\nDisponível na Apolo Veículos – agende seu test drive e descubra a sensação de dirigir um conversível premium da BMW\n\n', '2025-05-22', 'disponivel', '08c541414ce1536220cce5423d99e35b.jpg', 'c9cdec83e7c3533ef5eb258441a94cea.jpg', '74a5cd70aa9a33ded3dd663156009369.jpg', '60cafee8700d76cd82def61b10d4aebe.jpg'),
(112, 'HR-V', 'Honda', '2016', 'HONDA HR-V 1.8 16V FLEX LX 4P AUTOMÁTICO', 40000, '84500', '90000', 'prata', 'SUVS', 'HONDA HR-V 1.8 FLEX LX AUTOMÁTICO – CONFORTO, ESPAÇO E ECONOMIA NO SUV URBANO DA HONDA\r\nVersatilidade, confiabilidade e ótimo custo-benefício reunidos em um SUV com ótimo desempenho e excelente reputação no mercado. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2016\r\nMotor: 1.8 16V i-VTEC Flex – 140 cv (etanol) / 139 cv (gasolina)\r\nTorque: 17,4 kgfm\r\nCâmbio automático do tipo CVT\r\nConsumo médio: até 12 km/l na estrada (gasolina)\r\nPorta-malas com 437 litros\r\nSuspensão elevada e ótimo espaço interno\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia com conectividade Bluetooth e entrada USB\r\nAr-condicionado\r\nDireção elétrica progressiva\r\nCâmera de ré integrada\r\nVidros e travas elétricas nas quatro portas\r\nComputador de bordo e volante multifuncional\r\nBancos traseiros com sistema de rebatimento Magic Seat\r\nFreios ABS com EBD e airbags frontais\r\nChave com telecomando e alarme\r\n\r\nVeículo revisado, periciado e com garantia\r\nDocumentação em dia\r\nDisponível na Apolo Veículos com condições especiais\r\nFale com um consultor e agende seu test drive', '2025-05-22', 'disponivel', '12e934714b0a5597e10ba99b467af9e8.jpg', '1a3d54677146037be78183ee07762ee5.jpg', 'a336aa28faf5f3e215ca190d191cb156.jpg', '93c26a7e301068e83dfe8959e9e31940.jpg'),
(113, 'HR-V', 'Honda', '2016', 'HONDA HR-V 1.8 16V FLEX LX 4P AUTOMÁTICO', 40000, '84500', '83000', 'branco', 'SUVS', 'HONDA HR-V 1.8 FLEX LX AUTOMÁTICO – CONFORTO, ESPAÇO E ECONOMIA NO SUV URBANO DA HONDA\r\nVersatilidade, confiabilidade e ótimo custo-benefício reunidos em um SUV com ótimo desempenho e excelente reputação no mercado. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2016\r\nMotor: 1.8 16V i-VTEC Flex – 140 cv (etanol) / 139 cv (gasolina)\r\nTorque: 17,4 kgfm\r\nCâmbio automático do tipo CVT\r\nConsumo médio: até 12 km/l na estrada (gasolina)\r\nPorta-malas com 437 litros\r\nSuspensão elevada e ótimo espaço interno\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia com conectividade Bluetooth e entrada USB\r\nAr-condicionado\r\nDireção elétrica progressiva\r\nCâmera de ré integrada\r\nVidros e travas elétricas nas quatro portas\r\nComputador de bordo e volante multifuncional\r\nBancos traseiros com sistema de rebatimento Magic Seat\r\nFreios ABS com EBD e airbags frontais\r\nChave com telecomando e alarme\r\n\r\nVeículo revisado, periciado e com garantia\r\nDocumentação em dia\r\nDisponível na Apolo Veículos com condições especiais\r\nFale com um consultor e agende seu test drive', '2025-05-22', 'disponivel', 'd071951d43f6ea115472a19d00ab1378.jpg', '267c953f3f1058dd69d2681e8968fe57.jpg', '9941a38b56c3d28fdc01843e7350c225.jpg', '29e9854ac34e497b669db2edc2157a85.jpg'),
(99, 'Grand Siena', 'Fiat', '2021', '1.4 MPI ATTRACTIVE 8V FLEX 4P MANUAL', 20000, '44000', '60000', 'Branco', 'SEDANS', 'FIAT GRAND SIENA 1.4 ATTRACTIVE – ESPAÇO, ECONOMIA E CONFIANÇA\r\nO sedã ideal para quem busca conforto, robustez e ótimo custo-benefício. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2021\r\nMotor: 1.4 MPI Flex – 88 cv (etanol) / 85 cv (gasolina)\r\nTorque: 12,5 kgfm\r\nCâmbio manual de 5 marchas\r\nDireção hidráulica\r\nPorta-malas amplo com 520 litros\r\nConsumo médio: até 12,3 km/l na estrada (gasolina)\r\nBaixo custo de manutenção\r\n\r\nTecnologia e Conforto:\r\nAr-condicionado\r\nVidros e travas elétricas\r\nComputador de bordo\r\nSistema de som com rádio, USB e Bluetooth\r\nVolante com comandos de mídia\r\nAlarme e chave com telecomando\r\n\r\nVeículo com histórico aprovado e garantia\r\nDocumentação em dia\r\nVisite a Apolo Veículos e conheça de perto esse excelente sedã\r\nFale com um de nossos consultores e agende seu test drive', '2025-05-17', 'vendido', '97fe0099485944c574e6c1eeec9bb7db.jpg', 'ea61145d0b7b7b4148d715bd082db5ec.jpg', 'cae61476464a417c170a09bbbb3df803.jpg', '9dd62745b700d777ba09a7de379f8171.jpg'),
(119, 'X3', 'BMW', '2021', '2.0 16V HÍBRIDO XDRIVE30E STEPTRONIC', 20000, '78000', '669936', 'azul', 'SUVS', 'BMW X3 xDRIVE30e 2.0 HÍBRIDO – SOFISTICAÇÃO, EFICIÊNCIA E TRAÇÃO INTELIGENTE EM UM SÓ SUV\r\nO equilíbrio perfeito entre potência, tecnologia e consciência ambiental. Um SUV premium com desempenho esportivo e eficiência híbrida. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nMotorização: 2.0 TwinPower Turbo + motor elétrico (híbrido plug-in) – 292 cv combinados\r\nTorque: 42,8 kgfm\r\nCâmbio automático Steptronic de 8 marchas com paddle shifts\r\nTração integral xDrive inteligente\r\nAutonomia elétrica de até 50 km (modo EV)\r\nAceleração de 0 a 100 km/h em 6,1 segundos\r\nSuspensão com acerto esportivo e conforto premium\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia iDrive com tela sensível ao toque e conectividade sem fio\r\nPainel digital BMW Live Cockpit Professional\r\nAr-condicionado digital com controle de 3 zonas\r\nAssistentes de condução (controle de cruzeiro adaptativo, assistente de faixa, frenagem de emergência)\r\nChave presencial com partida por botão\r\nFaróis Full LED com acendimento automático\r\nBancos em couro com ajustes elétricos e memória\r\nPorta-malas com abertura elétrica e função mãos-livres\r\nRodas de liga leve BMW aro 19\"\r\n\r\nVeículo híbrido com excelente desempenho e baixo consumo\r\nRevisado, com documentação em dia e procedência garantida\r\nDisponível na Apolo Veículos – entre em contato e agende seu test drive', '2025-05-22', 'disponivel', '6fc69a58265ee3652bfd0142bdf62714.jpg', 'd4e5c0eb08e4da75461568d55f7ae843.jpg', 'be38a9f3ddd4318d0c22521144850a7d.jpg', '1a2ee74f97bc05692937f9009fdcf187.jpg'),
(118, 'X3', 'BMW', '2021', '2.0 16V HÍBRIDO XDRIVE30E STEPTRONIC', 20000, '78000', '999936', 'branco', 'SUVS', 'BMW X3 xDRIVE30e 2.0 HÍBRIDO – SOFISTICAÇÃO, EFICIÊNCIA E TRAÇÃO INTELIGENTE EM UM SÓ SUV\r\nO equilíbrio perfeito entre potência, tecnologia e consciência ambiental. Um SUV premium com desempenho esportivo e eficiência híbrida. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nMotorização: 2.0 TwinPower Turbo + motor elétrico (híbrido plug-in) – 292 cv combinados\r\nTorque: 42,8 kgfm\r\nCâmbio automático Steptronic de 8 marchas com paddle shifts\r\nTração integral xDrive inteligente\r\nAutonomia elétrica de até 50 km (modo EV)\r\nAceleração de 0 a 100 km/h em 6,1 segundos\r\nSuspensão com acerto esportivo e conforto premium\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia iDrive com tela sensível ao toque e conectividade sem fio\r\nPainel digital BMW Live Cockpit Professional\r\nAr-condicionado digital com controle de 3 zonas\r\nAssistentes de condução (controle de cruzeiro adaptativo, assistente de faixa, frenagem de emergência)\r\nChave presencial com partida por botão\r\nFaróis Full LED com acendimento automático\r\nBancos em couro com ajustes elétricos e memória\r\nPorta-malas com abertura elétrica e função mãos-livres\r\nRodas de liga leve BMW aro 19\"\r\n\r\nVeículo híbrido com excelente desempenho e baixo consumo\r\nRevisado, com documentação em dia e procedência garantida\r\nDisponível na Apolo Veículos – entre em contato e agende seu test drive', '2025-05-22', 'disponivel', 'ab533d0eeac04d01028d3c9c94eb5b3c.jpg', '27a7521759838cb47a40bd28d62f1661.jpg', '856693ca0408feb08647f9329c4414b1.jpg', 'c1293f476f9f1a2d0344015d10a0eb6a.jpg'),
(104, 'Nivus', 'Chevrolet', '2024', '1.0 200 TSI TOTAL FLEX HIGHLINE AUTOMÁTICO', 3000, '120000', '170000', 'Vermelho', 'SUVS', 'VOLKSWAGEN NIVUS 1.0 200 TSI HIGHLINE AUTOMÁTICO – DESIGN MODERNO, TECNOLOGIA E PERFORMANCE TURBO\r\nO SUV cupê da Volkswagen que se destaca pelo visual esportivo, excelente desempenho e alta conectividade. Versão topo de linha disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nAno/Modelo: 2021 (ou atualize conforme o modelo)\r\nMotor: 1.0 TSI Flex – 128 cv (etanol) / 116 cv (gasolina)\r\nTorque: 20,4 kgfm com injeção direta\r\nCâmbio automático de 6 marchas\r\nAceleração de 0 a 100 km/h em 10 segundos\r\nConsumo médio: até 14 km/l na estrada (gasolina)\r\nPorta-malas com 415 litros\r\n\r\nTecnologia e Conforto:\r\nCentral multimídia VW Play com tela de 10,1\" sensível ao toque\r\nPainel digital (Active Info Display)\r\nChave presencial com partida por botão (Keyless Entry & Go)\r\nAr-condicionado digital\r\nControle de estabilidade (ESC) e tração (ASR)\r\nAssistente de partida em rampa (HSA)\r\nSensor de chuva e crepuscular\r\nBancos em couro, volante multifuncional e acabamento premium\r\nSistema de frenagem automática pós-colisão\r\n\r\nVeículo periciado e com garantia\r\nDocumentação em dia\r\nNa Apolo Veículos, você encontra qualidade, procedência e as melhores condições\r\nEntre em contato com nossa equipe e agende seu test drive', '2025-05-20', 'vendido', 'e65d3b92b3a267e0dfddbb56b5f421a7.jpg', 'f2c20f6ab937cd9ac6ca61e95c91640b.jpg', 'e04cf079b056c06267f3a0f33a868179.jpg', 'e7c279ec465db742b7a8c9244336f1b1.jpg'),
(121, '320i', 'BMW', '2023', '2.0 16V TURBO FLEX M SPORT AUTOMÁTICO', 6300, '300000', '450000', 'preto', 'SUVS', 'BMW 320i M SPORT 2.0 TURBO FLEX AUTOMÁTICO – ESPORTIVIDADE, TECNOLOGIA E ELEGÂNCIA EM UM SEDÃ EXECUTIVO\r\nDesign imponente, dirigibilidade refinada e o DNA esportivo da linha M em um dos sedãs mais desejados do mercado. Disponível na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nMotorização: 2.0 TwinPower Turbo Flex – 184 cv\r\nTorque: 30,6 kgfm\r\nCâmbio automático Steptronic de 8 marchas com paddle shifts\r\nAceleração de 0 a 100 km/h em 7,1 segundos\r\nPacote M Sport: para-choques exclusivos, volante esportivo, acabamento interno refinado\r\nSuspensão com acerto esportivo M\r\nTração traseira (RWD)\r\n\r\nTecnologia e Conforto:\r\nPainel 100% digital com BMW Live Cockpit\r\nCentral multimídia iDrive com tela de 10,25\" e conectividade Apple CarPlay/Android Auto\r\nBancos esportivos em couro com ajustes elétricos e memória\r\nAr-condicionado digital Dual Zone\r\nFaróis Full LED com acendimento automático\r\nChave presencial com partida por botão\r\nAssistente de estacionamento, sensores e câmera de ré\r\nRodas de liga leve M aro 18\"\r\n\r\nVeículo de alto padrão, revisado, com procedência e garantia\r\nDocumentação em dia\r\nDisponível na Apolo Veículos – agende seu test drive e descubra o prazer de dirigir um verdadeiro BMW', '2025-05-22', 'disponivel', 'a3b6f9d79cd1d37542e020673a7e5ab8.jpg', '7c34ac65cc763916324e88cab2052471.jpg', 'c4af23d6b27ca2f099dfb51efe0a4100.jpg', '196614132341f14a1344cc2cdbcfb79f.jpg'),
(124, 'M3 GTR', 'BMW', '2024', 'V8 4.0 aspirado – 460 cv', 0, '193290', '2455990', 'azul', 'SEDANS', 'BMW M3 GTR – EDIÇÃO LEGENDARIA, EXCLUSIVA DA APOLO VEÍCULOS\r\nO carro mais icônico da história dos games agora pode ser seu. A lendária máquina do Need for Speed: Most Wanted ganhou vida em uma recriação oficial feita pela BMW, com base em um verdadeiro campeão das pistas. Essa unidade única está disponível exclusivamente na Apolo Veículos.\r\n\r\nDestaques do veículo:\r\nModelo: BMW M3 GTR – Edição Especial Most Wanted\r\nMotorização: V8 4.0 aspirado – 460 cv\r\nTração traseira (RWD)\r\nCâmbio sequencial de alta performance\r\nAceleração brutal e comportamento esportivo de competição\r\nBaseado em um ex-M3 GT de corrida\r\nVisual idêntico ao do game: carroceria alargada, pintura prata com listras azuis e spoiler traseiro marcante\r\nConstrução com peças em fibra de carbono e componentes de competição\r\n\r\nTecnologia e Interior:\r\nInterior aliviado com acabamento racing\r\nSanto antônio, bancos concha e cintos de segurança de 6 pontos\r\nPainel analógico retrabalhado com elementos digitais\r\nSistema de telemetria e controle de pista\r\nChave de competição personalizada\r\nNúmero de série exclusivo\r\nAutenticidade validada pela BMW\r\n\r\nUm ícone. Uma lenda. Uma oportunidade única.\r\nEsse é o tipo de carro que aparece uma vez na vida. Uma peça de coleção, feita para verdadeiros apaixonados por velocidade, história e cultura automotiva.\r\n\r\nDisponível exclusivamente na Apolo Veículos\r\nEntre em contato agora e conheça de perto essa obra-prima da engenharia e da nostalgia', '2025-05-22', 'disponivel', '40ccd89650109c0c078a3c01964ee236.jpg', '6b079cf140e0dfc7f0e1a98b8ffcd840.jpg', '392da589003ee2d7ab2cb806cb265115.jpg', '588e2d31958c5a674285605228d51952.jpg');

-- --------------------------------------------------------

--
-- Estrutura para tabela `cliente`
--

DROP TABLE IF EXISTS `cliente`;
CREATE TABLE IF NOT EXISTS `cliente` (
  `idCliente` int NOT NULL AUTO_INCREMENT,
  `cpfCliente` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `nomeCliente` varchar(100) COLLATE utf8mb3_unicode_ci NOT NULL,
  `emailCliente` varchar(100) COLLATE utf8mb3_unicode_ci NOT NULL,
  `telefoneCliente` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  PRIMARY KEY (`idCliente`)
) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Despejando dados para a tabela `cliente`
--

INSERT INTO `cliente` (`idCliente`, `cpfCliente`, `nomeCliente`, `emailCliente`, `telefoneCliente`) VALUES
(9, '478.597.388-99', 'Kayky Bezerra', 'menezeskayky16@gmail.com', '(11) 13214-2342'),
(10, '796.228.130-89', 'Hugo Andrade', 'hugo@gmail.com', '(11) 94732-6263'),
(11, '941.307.410-04', 'Diego Garcia', 'diego@gmail.com', '(11) 94784-9783'),
(12, '651.168.200-50', 'William Alves', 'william@gmail.com', '(11) 89492-3843'),
(13, '388.770.948-93', 'Ana Luisa', 'analu@gmail.com', '(11) 98832-4673');

-- --------------------------------------------------------

--
-- Estrutura para tabela `negociacao`
--

DROP TABLE IF EXISTS `negociacao`;
CREATE TABLE IF NOT EXISTS `negociacao` (
  `idNegoc` int NOT NULL AUTO_INCREMENT,
  `idCliente` int NOT NULL,
  `idCarro` int NOT NULL,
  `idVendedor` int DEFAULT NULL,
  `dtaSolic` date NOT NULL,
  `dtaInicioContato` date DEFAULT NULL,
  `dtaConclusao` date NOT NULL,
  `statusNegoc` varchar(20) COLLATE utf8mb3_unicode_ci NOT NULL,
  `valorVenda` int NOT NULL,
  PRIMARY KEY (`idNegoc`)
) ENGINE=MyISAM AUTO_INCREMENT=37 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Despejando dados para a tabela `negociacao`
--

INSERT INTO `negociacao` (`idNegoc`, `idCliente`, `idCarro`, `idVendedor`, `dtaSolic`, `dtaInicioContato`, `dtaConclusao`, `statusNegoc`, `valorVenda`) VALUES
(22, 10, 85, 1, '2025-05-17', '2025-05-17', '0000-00-00', 'cancelado', 0),
(25, 13, 99, 1, '2025-05-17', '2025-05-17', '2025-04-10', 'vendido', 0),
(35, 9, 107, 1, '2025-05-20', '2025-05-20', '2025-05-20', 'vendido', 200000),
(36, 12, 107, 1, '2025-05-20', '2025-05-20', '2025-05-20', 'cancelado', 0),
(33, 9, 104, 1, '2025-05-20', '2025-05-20', '2025-05-20', 'vendido', 190000),
(34, 12, 104, 1, '2025-05-20', '2025-05-20', '2025-05-20', 'cancelado', 0);

-- --------------------------------------------------------

--
-- Estrutura para tabela `vendedor`
--

DROP TABLE IF EXISTS `vendedor`;
CREATE TABLE IF NOT EXISTS `vendedor` (
  `idVendedor` int NOT NULL AUTO_INCREMENT,
  `nomeVendedor` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `cpfVendedor` varchar(15) COLLATE utf8mb3_unicode_ci NOT NULL,
  `senhaVendedor` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  PRIMARY KEY (`idVendedor`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Despejando dados para a tabela `vendedor`
--

INSERT INTO `vendedor` (`idVendedor`, `nomeVendedor`, `cpfVendedor`, `senhaVendedor`) VALUES
(1, 'Hugo Andrade', '12312312312', '202cb962ac59075b964b07152d234b70');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
